apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "lk"
  description: "kj"
  annotations:
    github.com/project-slug: blamdemo/ggg
    backstage.io/techdocs-ref: url:https://github.com/blamdemo/ggg
spec:
  type: documentation
  lifecycle: experimental
  owner: "kj"
